### ISSUE TITLE
Having trouble setting it up

### ISSUE THREAD

**Issue by JohnBakery** [synackSA/casperjs-php#1]
I'm new to this whole composer thing and I'm having trouble setting this dependency. I downloaded composer.json and placed it in my project folder. In the command prompt I ran 

`composer require synacksa/casperjs-php`

I got the following error message

> [InvalidArgumentException]
  Could not find package synacksa/casperjs-php at any version for your minimum-stability (stable). Check the package  spelling or your minimum-stability

I tried running the following command

`composer require "synacksa/casperjs-php:*"`

and I got this error

> ./composer.json has been updated
Root package 'synacksa/casperjs-php' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?

What am I doing wrong?

**Comment by synackSA** [comment]
Add the following line to your composer.json and you should be good to go.

`  "minimum-stability": "dev"`

**Comment by JohnBakery** [comment]
@synackSA Thank you for the tip. I actually managed to install it without the composer.json file. Without it, it installed with no issues whatsoever. 

I got another question. Is there a way to do casper.exists in casperjs-php?

**Comment by synackSA** [comment]
You can try it with a custom segment and addstep()

**Comment by synackSA** [comment]
Can I close this?
